repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
    -   id: ruff-format
        args: ["--line-length", "120"]  # Set your desired line length here
    -   id: ruff
        args: ["--ignore", "E714,E713,E711,E741,E722,E731"]  # Ignore E714 errors
